name: rate_in_store
description: A flutter rate plugin.
version: 0.0.1
author: brant <sjwu1234@gmail.com>
homepage: https://github.com/chinabrant/rate_in_store

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^5.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.hellotalk.rate_in_store
    pluginClass: RateInStorePlugin

  